name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Create .env file from GitHub secrets
        run: |
          echo "MY_SECRET_KEY=${{ secrets.PROD_SECRET_KEY }}" >> .env
          echo "ANOTHER_KEY=${{ secrets.ANOTHER_KEY }}" >> .env
          echo ".env file created:"
          cat .env

      - name: Install dependencies
        run: npm ci

      - name: Build project (if applicable)
        run: npm run build --if-present

     

   
